name: Auto-Label Issues Based on Title

on:
  issues:
    types: [opened, edited]

concurrency:
  group: issue-${{ github.event.issue.number }}
  cancel-in-progress: true

jobs:
  label_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Sync labels based on title
        if: github.event.issue.title != ''
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.issue.title.toLowerCase();
            const issue_number = context.payload.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const currentLabels = context.payload.issue.labels.map(label => label.name);

            let shouldHaveEnhancement = title.includes('feat');
            let shouldHaveBug = title.includes('fix') || title.includes('bug');

            let newLabels = [...currentLabels];

            // Manage 'enhancement' label
            if (shouldHaveEnhancement && !currentLabels.includes('enhancement')) {
              newLabels.push('enhancement');
            } else if (!shouldHaveEnhancement && currentLabels.includes('enhancement')) {
              newLabels = newLabels.filter(label => label !== 'enhancement');
            }

            // Manage 'bug' label
            if (shouldHaveBug && !currentLabels.includes('bug')) {
              newLabels.push('bug');
            } else if (!shouldHaveBug && currentLabels.includes('bug')) {
              newLabels = newLabels.filter(label => label !== 'bug');
            }

            // Update labels if necessary
            await github.rest.issues.setLabels({
              owner,
              repo,
              issue_number,
              labels: newLabels
            });
